# The helloserver pod has two containers:
#   An HTTP server that displays "Hello, world"
#   A file integrity monitoring sidecar
apiVersion: v1
kind: Pod
metadata:
  name: helloserver
  labels:
    app: helloserver
spec:
  shareProcessNamespace: true
  containers:
    # The "Hello, world" application container
    - image: hello_server:1.0
      name: helloserver
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
          
    # The sidecar container
    - image: fim:1.0
      name: fim
      # We need to run as privileged to access
      # the files in the helloserver container
      securityContext:
        privileged: true
      livenessProbe:
        # We check that the application server
        # hasn't been compromised by checking that
        # the hash of index.html is 746308...
        exec:
          command:
          - /bin/ash
          - /healthz
          - /home/hellouser/index.html
          - 746308829575e17c3331bbcb00c0898b
