apiVersion: v1
kind: Pod
metadata:
  name: helloserver
  labels:
    app: helloserver
spec:
  shareProcessNamespace: true
  containers:
    - image: hello_server:1.0
      name: helloserver
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
    - image: fim:1.0
      name: fim
      securityContext:
        privileged: true
      livenessProbe:
        exec:
          command:
          - /bin/ash
          - /healthz
          - /home/hellouser/index.html
          - 746308829575e17c3331bbcb00c0898b
