apiVersion: v1
kind: Service
metadata:
  name: helloservice
  labels:
    app: helloservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: helloserver
  type: LoadBalancer
