apiVersion: v1
kind: Pod
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  shareProcessNamespace: true
  containers:
    - image: httpserver:1.0
      name: httpserver
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
    - image: fim:1.0
      name: fim
      livenessProbe:
        exec:
          command:
          - /bin/ash
          - /healthz
