# We expose the helloserver pod via a
# LoadBalancer service that listens on
# port 80 and routes requests to port
# 8000 of the pod.
apiVersion: v1
kind: Service
metadata:
  name: helloservice
  labels:
    app: helloservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: helloserver
  type: LoadBalancer
