# We expose the hello-server pod via a
# LoadBalancer service that listens on
# port 80 and routes requests to port
# 8000 of the pod.
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello-server
  type: LoadBalancer
