name: build-containers
on:
  workflow_dispatch

jobs:
  build-job:
    name: 'Build Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Log in to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push hello-server
        uses: docker/build-push-action@v5
        with:
          context: containers/hello_server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hammingweight/hello_server:1.0.2
      - name: Build and push FIM sidecar
        uses: docker/build-push-action@v5
        with:
          context: containers/fim
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hammingweight/fim:1.0.1
